spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: book_db
logging:
  level:
    org.springframework.data.mongodb.core: debug
server:
  port: 8888
  error:
    include-message: always